sudo: required
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=7

services:
  - docker
  - postgresql



before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull centos:centos${OS_VERSION}

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

language: ruby
rvm:
  - 2.3
script:
  - bundle exec rspec
