env:
  matrix:
  - OS_TYPE=centos OS_VERSION=7

services:
  - postgresql

language: ruby
rvm:
  - 2.3.3

before_script:
    - cp config/database.travis.yml config/database.yml
    - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rspec
